name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout de repository met LFS-bestanden
      - name: Checkout repository met Git LFS
        uses: actions/checkout@v2
        with:
          lfs: true

      # 2. Optioneel: Zorg er extra voor dat Git LFS-bestanden worden opgehaald
      - name: Git LFS pull
        run: git lfs pull

      # 3. Installeer je afhankelijkheden en bouw het project
      - name: Installeer dependencies
        run: npm install

      - name: Bouw project
        run: npm run build

      # 4. Deploy stap (pas deze stap aan op jouw deployment proces)
      - name: Deploy website
        run: |
          echo "Hier deployen we de website, bijvoorbeeld naar GitHub Pages, een VPS of een CDN."
          # Voeg hier je deploy commando's toe
